FROM ubuntu:18.04

LABEL maintainer="dla9944@naver.com"



RUN apt-get update

RUN apt-get install -y apache2 apt-utils


COPY ./EWS_diary /var/www/html/

EXPOSE 80

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
