version: "3"

services:
  webserver:
    image: nginx:latest
    container_name: proxy0612
    restart: always
    ports:
      - "7070:80"
      - "443:443"
    volumes:
      - ./myweb:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx:
    image: nginx:latest
    container_name: myweb0612
    restart: always
    volumes:
      - ./myweb:/usr/share/nginx/html

