version: "3"


services:
  nginxproxy:
    depends_on:
      - nginx
      - db
      - wordpress
    image: nginx:latest
    ports:
      - "9999:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  # nginx was not considered specific version
  nginx:
    image: nginx:latest
    restart: always

  db:
    image: mysql:5.7
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: 9026
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 9026

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.0
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 9026
      WORDPRESS_DB_NAME: wordpress
