version: "3"


services:
  nginxproxy:
    depends_on:
      - nginx
      - db
      - wordpress
    image: nginx:latest
    container_name: proxy
    ports:
      - "9999:80"
    restart: always
    # docker 복사 
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  # nginx was not considered specific version
  nginx:
    image: nginx:latest
    container_name: portpolio
    restart: always
    volumes:
      - "./portpolio:/usr/share/nginx/html"

  db:
    image: mysql:5.7
    container_name: mysqldb
    volumes:
      - "mydb:/var/lib/mysql"
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: 9026
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 9026

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./html:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 9026
      WORDPRESS_DB_NAME: wordpress

volumes:        
  mydb:
