version: "3"


services:
  nginxproxy:
    depends_on:
      - nginx
      - db
      - wordpress
    image: nginx.latest
    ports:
      - "9999:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"

  nginx:
    image: nginx:latest

